// Compilation of the 1000 most commonly used English words as per https://www.ef.com/wwen/english-resources/english-vocabulary/top-1000-words/
// Removed single letter words and proper nouns

const words = [
  "ability", "able", "about", "above", "accept", "according", "account", "across", "act", "action", "activity", "actually", "add", "address", "administration", "admit", "adult", "affect", "after", "again", "against", "age", "agency", "agent", "ago", "agree", "agreement", "ahead", "air", "all", "allow", "almost", "alone", "along", "already", "also", "although", "always", "among", "amount", "analysis", "and", "animal", "another", "answer", "any", "anyone", "anything", "appear", "apply", "approach", "area", "argue", "arm", "around", "arrive", "art", "article", "artist", "as", "ask", "assume", "at", "attack", "attention", "attorney", "audience", "author", "authority", "available", "avoid", "away", "baby", "back", "bad", "bag", "ball", "bank", "bar", "base", "be", "beat", "beautiful", "because", "become", "bed", "before", "begin", "behavior", "behind", "believe", "benefit", "best", "better", "between", "beyond", "big", "bill", "billion", "bit", "black", "blood", "blue", "board", "body", "book", "born", "both", "box", "boy", "break", "bring", "brother", "budget", "build", "building", "business", "but", "buy", "by", "call", "camera", "campaign", "can", "cancer", "candidate", "capital", "car", "card", "care", "career", "carry", "case", "catch", "cause", "cell", "center", "central", "century", "certain", "certainly", "chair", "challenge", "chance", "change", "character", "charge", "check", "child", "choice", "choose", "church", "citizen", "city", "civil", "claim", "class", "clear", "clearly", "close", "coach", "cold", "collection", "college", "color", "come", "commercial", "common", "community", "company", "compare", "computer", "concern", "condition", "conference", "consider", "consumer", "contain", "continue", "control", "cost", "could", "country", "couple", "course", "court", "cover", "create", "crime", "cultural", "culture", "cup", "current", "customer", "cut", "dark", "data", "daughter", "day", "dead", "deal", "death", "debate", "decade", "decide", "decision", "deep", "defense", "degree", "democratic", "describe", "design", "despite", "detail", "determine", "develop", "development", "die", "difference", "different", "difficult", "dinner", "direction", "director", "discover", "discuss", "discussion", "disease", "do", "doctor", "dog", "door", "down", "draw", "dream", "drive", "drop", "drug", "during", "each", "early", "east", "easy", "eat", "economic", "economy", "edge", "education", "effect", "effort", "eight", "either", "election", "else", "employee", "end", "energy", "enjoy", "enough", "enter", "entire", "environment", "environmental", "especially", "establish", "even", "evening", "event", "ever", "every", "everybody", "everyone", "everything", "evidence", "exactly", "example", "executive", "exist", "expect", "experience", "expert", "explain", "eye", "face", "fact", "factor", "fail", "fall", "family", "far", "fast", "father", "fear", "federal", "feel", "feeling", "few", "field", "fight", "figure", "fill", "film", "final", "finally", "financial", "find", "fine", "finger", "finish", "fire", "firm", "first", "fish", "five", "floor", "fly", "focus", "follow", "food", "foot", "for", "force", "foreign", "forget", "form", "former", "forward", "four", "free", "friend", "from", "front", "full", "fund", "future", "game", "garden", "gas", "general", "generation", "get", "girl", "give", "glass", "go", "goal", "good", "government", "great", "green", "ground", "group", "grow", "growth", "guess", "gun", "guy", "hair", "half", "hand", "hang", "happen", "happy", "hard", "have", "he", "head", "health", "hear", "heart", "heat", "heavy", "help", "her", "here", "herself", "high", "him", "himself", "his", "history", "hit", "hold", "home", "hope", "hospital", "hot", "hotel", "hour", "house", "how", "however", "huge", "human", "hundred", "husband", "idea", "identify", "if", "image", "imagine", "impact", "important", "improve", "in", "include", "including", "increase", "indeed", "indicate", "individual", "industry", "information", "inside", "instead", "institution", "interest", "interesting", "international", "interview", "into", "investment", "involve", "issue", "it", "item", "its", "itself", "job", "join", "just", "keep", "key", "kid", "kill", "kind", "kitchen", "know", "knowledge", "land", "language", "large", "last", "late", "later", "laugh", "law", "lawyer", "lay", "lead", "leader", "learn", "least", "leave", "left", "leg", "legal", "less", "let", "letter", "level", "lie", "life", "light", "like", "likely", "line", "list", "listen", "little", "live", "local", "long", "look", "lose", "loss", "lot", "love", "low", "machine", "magazine", "main", "maintain", "major", "majority", "make", "man", "manage", "management", "manager", "many", "market", "marriage", "material", "matter", "may", "maybe", "me", "mean", "measure", "media", "medical", "meet", "meeting", "member", "memory", "mention", "message", "method", "middle", "might", "military", "million", "mind", "minute", "miss", "mission", "model", "modern", "moment", "money", "month", "more", "morning", "most", "mother", "mouth", "move", "movement", "movie", "much", "music", "must", "my", "myself", "name", "nation", "national", "natural", "nature", "near", "nearly", "necessary", "need", "network", "never", "new", "news", "newspaper", "next", "nice", "night", "no", "none", "nor", "north", "not", "note", "nothing", "notice", "now", "number", "occur", "of", "off", "offer", "office", "officer", "official", "often", "oh", "oil", "ok", "old", "on", "once", "one", "only", "onto", "open", "operation", "opportunity", "option", "or", "order", "organization", "other", "others", "our", "out", "outside", "over", "own", "owner", "page", "pain", "painting", "paper", "parent", "part", "participant", "particular", "particularly", "partner", "party", "pass", "past", "patient", "pattern", "pay", "peace", "people", "per", "perform", "performance", "perhaps", "period", "person", "personal", "phone", "physical", "pick", "picture", "piece", "place", "plan", "plant", "play", "player", "point", "police", "policy", "political", "politics", "poor", "popular", "population", "position", "positive", "possible", "power", "practice", "prepare", "present", "president", "pressure", "pretty", "prevent", "price", "private", "probably", "problem", "process", "produce", "product", "production", "professional", "professor", "program", "project", "property", "protect", "prove", "provide", "public", "pull", "purpose", "push", "put", "quality", "question", "quickly", "quite", "race", "radio", "raise", "range", "rate", "rather", "reach", "read", "ready", "real", "reality", "realize", "really", "reason", "receive", "recent", "recently", "recognize", "record", "red", "reduce", "reflect", "region", "relate", "relationship", "religious", "remain", "remember", "remove", "report", "represent", "require", "research", "resource", "respond", "response", "responsibility", "rest", "result", "return", "reveal", "rich", "right", "rise", "risk", "road", "rock", "role", "room", "rule", "run", "safe", "same", "save", "say", "scene", "school", "science", "scientist", "score", "sea", "season", "seat", "second", "section", "security", "see", "seek", "seem", "sell", "send", "senior", "sense", "series", "serious", "serve", "service", "set", "seven", "several", "sex", "sexual", "shake", "share", "she", "shoot", "short", "shot", "should", "shoulder", "show", "side", "sign", "significant", "similar", "simple", "simply", "since", "sing", "single", "sister", "sit", "site", "situation", "six", "size", "skill", "skin", "small", "smile", "so", "social", "society", "soldier", "some", "somebody", "someone", "something", "sometimes", "son", "song", "soon", "sort", "sound", "source", "south", "southern", "space", "speak", "special", "specific", "speech", "spend", "sport", "spring", "staff", "stage", "stand", "standard", "star", "start", "state", "statement", "station", "stay", "step", "still", "stock", "stop", "store", "story", "strategy", "street", "strong", "structure", "student", "study", "stuff", "style", "subject", "success", "successful", "such", "suddenly", "suffer", "suggest", "summer", "support", "sure", "surface", "system", "table", "take", "talk", "task", "tax", "teach", "teacher", "team", "technology", "television", "tell", "ten", "tend", "term", "test", "than", "thank", "that", "the", "their", "them", "themselves", "then", "theory", "there", "these", "they", "thing", "think", "third", "this", "those", "though", "thought", "thousand", "threat", "three", "through", "throughout", "throw", "thus", "time", "to", "today", "together", "tonight", "too", "top", "total", "tough", "toward", "town", "trade", "traditional", "training", "travel", "treat", "treatment", "tree", "trial", "trip", "trouble", "true", "truth", "try", "turn", "two", "type", "under", "understand", "unit", "until", "up", "upon", "us", "use", "usually", "value", "various", "very", "victim", "view", "violence", "visit", "voice", "vote", "wait", "walk", "wall", "want", "war", "watch", "water", "way", "we", "weapon", "wear", "week", "weight", "well", "west", "western", "what", "whatever", "when", "where", "whether", "which", "while", "white", "who", "whole", "whom", "whose", "why", "wide", "wife", "will", "win", "wind", "window", "wish", "with", "within", "without", "woman", "wonder", "word", "work", "worker", "world", "worry", "would", "write", "writer", "wrong", "yard", "yeah", "year", "yes", "yet", "you", "young", "your", "yourself"
];

// Compilation of famous book and movie quotes
// Book quotes from https://www.bookbub.com/blog/famous-book-quotes
// Movie quotes from https://www.afi.com/afis-100-years-100-movie-quotes/

const quotes = [
  "There is some good in this world, and it’s worth fighting for.",
  "It is only with the heart that one can see rightly; what is essential is invisible to the eye.",
  "I am no bird; and no net ensnares me: I am a free human being with an independent will, which I now exert to leave you.",
  "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair.",
  "Beware; for I am fearless, and therefore powerful.",
  "I wanted you to see what real courage is, instead of getting the idea that courage is a man with a gun in his hand. It’s when you know you’re licked before you begin but you begin anyway and you see it through no matter what. You rarely win, but sometimes you do.",
  "A man, after he has brushed off the dust and chips of his life, will have left only the hard, clean questions: Was it good or was it evil? Have I done well — or ill?",
  "The only way out of the labyrinth of suffering is to forgive.",
  "This above all: To thine own self be true, And it must follow, as the night the day, Thou canst not then be false to any man.",
  "I took a deep breath and listened to the old brag of my heart: I am, I am, I am.",
  "Love is or it ain’t. Thin love ain’t love at all.",
  "We accept the love we think we deserve.",
  "And so we beat on, boats against the current, borne back ceaselessly into the past.",
  "Generally, by the time you are Real, most of your hair has been loved off, and your eyes drop out and you get loose in the joints and very shabby. But these things don’t matter at all, because once you are Real you can’t be ugly, except to people who don’t understand.",
  "Whatever our souls are made of, his and mine are the same.",
  "There are years that ask questions and years that answer.",
  "I am not afraid of storms, for I am learning how to sail my ship.",
  "All happy families are alike; each unhappy family is unhappy in its own way.",
  "Memories warm you up from the inside. But they also tear you apart.",
  "It is nothing to die; it is dreadful not to live.",
  "Who controls the past controls the future. Who controls the present controls the past.",
  "Life is to be lived, not controlled; and humanity is won by continuing to play in face of certain defeat.",
  "Last night I dreamt I went to Manderley again.",
  "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
  "Tomorrow I’ll think of some way to get him back. After all, tomorrow is another day.",
  "Why, sometimes, I’ve believed as many as six impossible things before breakfast.",
  "Don’t ever tell anybody anything. If you do, you start missing everybody.",
  "It does not do to dwell on dreams and forget to live.",
  "You pierce my soul. I am half agony. Half hope. Tell me not that I am too late, that such precious feelings are gone for ever.",
  "I had the epiphany that laughter was light, and light was laughter, and that this was the secret of the universe.",
  "‘Why did you do all this for me?’ he asked. ‘I don’t deserve it. I’ve never done anything for you.’ ‘You have been my friend,’ replied Charlotte. ‘That in itself is a tremendous thing.’",
  "There are some things you learn best in calm, and some in storm.",
  "When you play the game of thrones you win or you die.",
  "The world breaks everyone, and afterward, many are strong at the broken places.",
  "From that time on, the world was hers for the reading. She would never be lonely again, never miss the lack of intimate friends. Books became her friends and there was one for every mood.",
  "Once upon a time there was a boy who loved a girl, and her laughter was a question he wanted to spend his whole life answering.",
  "Very few castaways can claim to have survived so long at sea as Mr. Patel, and none in the company of an adult Bengal tiger.",
  "Anyone who ever gave you confidence, you owe them a lot.",
  "Isn’t it nice to think that tomorrow is a new day with no mistakes in it yet?",
  "You forget what you want to remember, and you remember what you want to forget.",
  "The past is not dead. In fact, it’s not even past.",
  "He has put a knife on the things that held us together and we have fallen apart.",
  "Memories, even your most precious ones, fade surprisingly quickly. But I don’t go along with that. The memories I value most, I don’t ever see them fading.",
  "Nowadays people know the price of everything and the value of nothing.",
  "Time is the longest distance between two places.",
  "The voice of the sea is seductive, never ceasing, whispering, clamoring, murmuring, inviting the soul to wander in abysses of solitude.",
  "We dream in our waking moments, and walk in our sleep.",
  "The place where you made your stand never mattered. Only that you were there… and still on your feet.",
  "But soft! What light through yonder window breaks? It is the east, and Juliet is the sun.",
  "My advice is, never do tomorrow what you can do today. Procrastination is the thief of time.",
  "So many things are possible just as long as you don’t know they’re impossible.",
  "I can’t stand it to think my life is going so fast and I’m not really living it.",
  "There is only one page left to write on. I will fill it with words of only one syllable. I love. I have loved. I will love.",
  "It doesn’t matter who you are or what you look like, so long as somebody loves you.",
  "The same substance composes us — the tree overhead, the stone beneath us, the bird, the beast, the star — we are all one, all moving to the same end.",
  "I wish, as well as everybody else, to be perfectly happy; but, like everybody else, it must be in my own way.",
  "Love is holy because it is like grace – the worthiness of its object is never really what matters.",
  "Each time you happen to me all over again.",
  "Brave doesn’t mean you’re not scared. It means you go on even though you’re scared.",
  "How easy it was to lie to strangers, to create with strangers the versions of our lives we imagined.",
  "And, when you want something, all the universe conspires in helping you to achieve it.",
  "Life, with its rules, its obligations, and its freedoms, is like a sonnet: You’re given the form, but you have to write the sonnet yourself.",
  "There is always something left to love.",
  "The answer to the ultimate question of life, the universe and everything is 42.",
  "All the world’s a stage, and all the men and women merely players. They have their exits and their entrances; And one man in his time plays many parts.",
  "Sometimes I can hear my bones straining under the weight of all the lives I’m not living.",
  "Do I love you? My God, if your love were a grain of sand, mine would be a universe of beaches.",
  "You don’t know about me without you have read a book by the name of The Adventures of Tom Sawyer, but that ain’t no matter.",
  "Love is the longing for the half of ourselves we have lost.",
  "It is our choices, Harry, that show what we truly are, far more than our abilities.",
  "Then you must teach my daughter this same lesson. How to lose your innocence but not your hope. How to laugh forever.",
  "Ralph wept for the end of innocence, the darkness of man’s heart, and the fall through the air of the true, wise friend called Piggy.",
  "All human wisdom is summed up in these two words – ‘Wait and hope.’",
  "Oh, the places you’ll go! You’ll be on your way up! You’ll be seeing great sights! You’ll join the high fliers who soar to high heights.",
  "The longer I live, the more uninformed I feel. Only the young have an explanation for everything.",
  "Open your eyes and see what you can with them before they close forever.",
  "If you have the guts to be yourself, other people’ll pay your price.",
  "We were the people who were not in the papers. We lived in the blank white spaces at the edges of print. It gave us more freedom. We lived in the gaps between the stories.",
  "As Gregor Samsa awoke one morning from uneasy dreams he found himself transformed in his bed into an enormous insect.",
  "We are such stuff as dreams are made on, and our little life is rounded with a sleep.",
  "The creatures outside looked from pig to man, and from man to pig, and from pig to man again; but already it was impossible to say which was which.",
  "Most men and women will grow up to love their servitude and will never dream of revolution.",
  "There is no greater agony than bearing an untold story inside you.",
  "As he read, I fell in love the way you fall asleep: slowly, and then all at once.",
  "All we can know is that we know nothing. And that’s the height of human wisdom.",
  "There is nothing like looking, if you want to find something. You certainly usually find something, if you look, but it is not always quite the something you were after.",
  "When you realize you want to spend the rest of your life with somebody, you want the rest of your life to start as soon as possible.",
  "If you let my daughter go now, that'll be the end of it. I will not look for you, I will not pursue you. But if you don't, I will look for you, I will find you, and I will kill you.",
  "Badges? We ain't got no badges! We don't need no badges! I don't have to show you any stinking badges!",
  "You don't understand! I coulda had class. I coulda been a contender. I could've been somebody, instead of a bum, which is what I am.",
  "Louis, I think this is the beginning of a beautiful friendship.",
  "A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti.",
  "Mama always said life was like a box of chocolates. You never know what you're gonna get.",
  "You've got to ask yourself one question: 'Do I feel lucky?' Well, do ya, punk?",
  "Listen to me, mister. You're my knight in shining armor. Don't you forget it. You're going to get back on that horse, and I'm going to be right behind you, holding on tight, and away we're gonna go, go, go!",
  "Cinderella story. Outta nowhere. A former greenskeeper, now, about to become the Masters champion. It looks like a mirac...It's in the hole! It's in the hole! It's in the hole!"
];

export {words, quotes};
